
#line 3 "lex.ce.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define yy_create_buffer ce_create_buffer
#define yy_delete_buffer ce_delete_buffer
#define yy_flex_debug ce_flex_debug
#define yy_init_buffer ce_init_buffer
#define yy_flush_buffer ce_flush_buffer
#define yy_load_buffer_state ce_load_buffer_state
#define yy_switch_to_buffer ce_switch_to_buffer
#define yyin cein
#define yyleng celeng
#define yylex celex
#define yylineno celineno
#define yyout ceout
#define yyrestart cerestart
#define yytext cetext
#define yywrap cewrap
#define yyalloc cealloc
#define yyrealloc cerealloc
#define yyfree cefree

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE cerestart(cein  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

extern int celeng;

extern FILE *cein, *ceout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up cetext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up cetext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via cerestart()), so that the user can continue scanning by
	 * just pointing cein at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when cetext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int celeng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow cewrap()'s to do buffer switches
 * instead of setting up a fresh cein.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void cerestart (FILE *input_file  );
void ce_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE ce_create_buffer (FILE *file,int size  );
void ce_delete_buffer (YY_BUFFER_STATE b  );
void ce_flush_buffer (YY_BUFFER_STATE b  );
void cepush_buffer_state (YY_BUFFER_STATE new_buffer  );
void cepop_buffer_state (void );

static void ceensure_buffer_stack (void );
static void ce_load_buffer_state (void );
static void ce_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER ce_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE ce_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE ce_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE ce_scan_bytes (yyconst char *bytes,int len  );

void *cealloc (yy_size_t  );
void *cerealloc (void *,yy_size_t  );
void cefree (void *  );

#define yy_new_buffer ce_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        ceensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            ce_create_buffer(cein,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        ceensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            ce_create_buffer(cein,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define cewrap(n) 1
#define YY_SKIP_YYWRAP

typedef unsigned char YY_CHAR;

FILE *cein = (FILE *) 0, *ceout = (FILE *) 0;

typedef int yy_state_type;

extern int celineno;

int celineno = 1;

extern char *cetext;
#define yytext_ptr cetext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up cetext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	celeng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 45
#define YY_END_OF_BUFFER 46
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_acclist[208] =
    {   0,
       46,   44,   45,   43,   44,   45,   43,   45,   39,   40,
       41,   42,   44,   45,   39,   40,   41,   42,   44,   45,
       40,   41,   42,   44,   45,   41,   42,   44,   45,   42,
       44,   45,   42,   44,   45,   42,   44,   45,   42,   44,
       45,   42,   44,   45,   44,   45,   44,   45,   44,   45,
       44,   45,   44,   45,   44,   45,   44,   45,   44,   45,
       44,   45,   44,   45,   44,   45,   42,   44,   45,   42,
       44,   45,   42,   44,   45,   42,   44,   45,   44,   45,
       44,   45,   44,   45,   44,   45,   44,   45,   44,   45,
       44,   45,   44,   45,   44,   45,   44,   45,   44,   45,

       39,   40,   41,   42,   40,   41,   42,   41,   42,   42,
       42,   42,   39,   40,   41,   42,   39,   40,   41,   42,
       40,   41,   42,   41,   42,   42,   42,   42,   40,   41,
       42,   41,   42,   42,   42,   42,   42,   42,   42,   42,
       18,   23,   24,   37,   42,   42,   42,   38,   38,   42,
       38,   42,   38,   42,    1,    4,    5,   11,   12,   14,
       14,   15,   17,   19,   19,   21,   22,   26,   28,   30,
       28,   32,   32,   33,   34,   36,   14,   19,   28,   32,
       33,   34,   38,   38,   38,   42,    3,    7,    9,    3,
        7,    9,   10,   13,   16,   20,   25,   27,   29,   31,

       35,    3,    7,    9,    2,    6,    8
    } ;

static yyconst flex_int16_t yy_accept[218] =
    {   0,
        1,    1,    1,    2,    4,    7,    9,   15,   21,   26,
       30,   33,   36,   39,   42,   45,   47,   49,   51,   53,
       55,   57,   59,   61,   63,   65,   67,   70,   73,   76,
       79,   81,   83,   85,   87,   89,   91,   93,   95,   97,
       99,  101,  105,  108,  110,  111,  112,  113,  117,  121,
      124,  126,  127,  128,  129,  132,  134,  135,  136,  137,
      137,  137,  137,  138,  139,  139,  139,  139,  140,  140,
      140,  140,  141,  141,  141,  141,  141,  141,  141,  141,
      141,  141,  142,  142,  142,  142,  142,  142,  142,  143,
      144,  145,  145,  145,  145,  145,  145,  145,  145,  145,

      145,  145,  145,  145,  145,  145,  145,  145,  145,  145,
      146,  147,  147,  147,  147,  148,  148,  148,  148,  148,
      148,  148,  148,  148,  148,  148,  148,  148,  148,  148,
      148,  148,  148,  148,  148,  148,  149,  151,  153,  155,
      156,  156,  157,  158,  158,  158,  158,  158,  158,  158,
      159,  160,  161,  161,  162,  163,  163,  163,  164,  165,
      166,  167,  168,  168,  169,  169,  170,  170,  171,  172,
      172,  173,  174,  175,  176,  176,  177,  177,  177,  177,
      177,  177,  178,  178,  179,  179,  180,  180,  181,  182,
      183,  183,  184,  185,  187,  188,  189,  190,  191,  192,

      193,  194,  195,  196,  197,  198,  199,  200,  201,  202,
      203,  204,  205,  206,  207,  208,  208
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    4,    5,    6,    7,    1,    8,    9,   10,
       11,   12,   12,   13,   12,   14,   14,    1,    1,    1,
        1,    1,    1,    1,   15,   16,   17,   18,   19,   20,
       21,   22,   23,    1,    1,   24,   25,   26,   27,   28,
       29,   30,   31,   32,   33,    1,    1,   34,    1,    1,
        1,    1,    1,    1,    1,    1,   35,   36,   37,   38,

       39,   40,   41,   42,   43,    1,    1,   44,   45,   46,
       47,   48,   49,   50,   51,   52,   53,    1,    1,   54,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[55] =
    {   0,
        1,    1,    1,    1,    2,    1,    2,    3,    3,    3,
        3,    3,    3,    3,    4,    1,    4,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    4,    1,    4,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1
    } ;

static yyconst flex_int16_t yy_base[219] =
    {   0,
        0,    0,  422,  423,  423,  423,   47,   83,   63,   68,
      119,  156,  153,   43,   75,  114,  115,  116,  117,  116,
      124,  159,  180,  133,   95,  152,  168,  174,  375,  370,
      373,   61,  371,  370,  366,  372,   74,  179,  379,  101,
       67,    0,  107,  225,  231,  267,    0,    0,    0,  176,
        0,    0,  278,    0,  144,    0,    0,  382,  385,  193,
      388,  395,  358,  361,  175,  364,  371,  375,  373,  373,
      371,  351,  349,  349,  347,  376,  355,  380,  359,  361,
      340,  423,  370,  349,  371,  350,  355,  334,  423,  423,
      243,  359,  360,  337,  338,  355,  350,  352,  332,  327,

      329,  349,  328,  360,  362,  344,  340,  322,  318,  316,
      319,  179,  322,  329,  313,  311,  311,  309,  318,  323,
      305,  315,  317,  302,  307,  308,  305,  300,  302,  302,
      334,  336,  298,  294,  220,  250,  242,  285,  243,  423,
      312,  423,  423,  316,  315,  289,  293,  292,  305,  423,
      423,  314,  283,  292,  423,  316,  295,  423,  321,  320,
      423,  423,  311,  423,  290,  305,  294,  423,  283,  272,
      301,  280,  423,  423,  291,  423,  270,  268,  272,  271,
      264,  273,  277,  303,  274,  269,  217,  226,  423,  423,
      216,  260,  292,    0,  193,  184,  179,  149,  148,  144,

      423,  423,  423,  423,  423,  423,  423,  423,  423,  107,
       75,   32,  423,  423,  423,  423,  304,  307
    } ;

static yyconst flex_int16_t yy_def[219] =
    {   0,
      216,    1,  216,  216,  216,  216,  216,  216,    8,    8,
      216,   11,   12,   12,   12,  216,  216,  216,  216,  216,
      216,  217,  216,  216,  216,  216,   12,   12,   12,   12,
      216,  216,  216,  216,  216,  216,  216,  216,  216,  216,
      216,    7,    7,    7,    7,   45,   46,    7,    8,    8,
       10,   12,   12,   53,    7,   44,   45,   12,   12,  216,
      216,  216,   12,   12,  216,  216,  216,   12,  216,  216,
      216,   12,  216,  216,  216,  216,  216,  216,  216,  216,
      216,  216,  216,  216,  216,  216,  216,  216,  216,  216,
      216,  216,  216,  216,  216,  216,  216,  216,  216,  216,

      216,  216,  216,  216,  216,  216,  216,  216,  216,   12,
       12,  216,  216,  216,   12,  216,  216,  216,  216,  216,
      216,  216,  216,  216,  216,  216,  216,  216,  216,  216,
      216,  216,  216,  216,  218,  216,   46,   45,   53,  216,
      216,  216,  216,  216,  216,  216,  216,  216,  216,  216,
      216,  216,  216,  216,  216,  216,  216,  216,  216,  216,
      216,  216,  216,  216,  216,  216,  216,  216,  216,  216,
      216,  216,  216,  216,  216,  216,  216,  216,  216,  216,
      216,  216,  216,  216,  216,  216,  216,  216,  216,  216,
      216,  218,  216,  138,  216,  216,  216,  216,  216,  216,

      216,  216,  216,  216,  216,  216,  216,  216,  216,  216,
      216,  216,  216,  216,  216,    0,  216,  216
    } ;

static yyconst flex_int16_t yy_nxt[478] =
    {   0,
        4,    5,    6,    4,    7,    4,    7,    8,    8,    9,
        9,    9,    9,   10,   11,   12,   13,   12,   14,   15,
        4,    4,   16,   17,   18,   19,   20,   21,    4,   22,
       23,   24,   25,   26,   27,   12,   28,   12,   29,   30,
        4,    4,   31,   32,   33,   34,   35,   36,    4,   37,
       38,   39,   40,   41,   42,   42,   43,   43,   43,   43,
       44,   45,   45,   45,   45,   46,   45,   55,   76,   55,
       50,   50,   56,  215,   56,   51,   51,   51,   51,   51,
       51,   45,   45,   45,   45,   47,   45,   48,   77,   48,
       49,   49,   50,   50,   50,   50,   51,   52,   52,   52,

       52,   53,   52,  104,   78,  105,   82,  122,  125,  131,
      126,  132,  133,  134,   43,   43,  214,   52,   52,   52,
       52,   54,   52,   57,   79,   57,   52,   52,   52,   52,
       52,   52,   52,   52,   58,   59,   52,   52,   52,   80,
       82,   83,   85,   87,   60,   89,   90,  102,  213,   61,
       62,   43,   43,   52,   63,   64,   52,   52,   52,   81,
       82,   84,   86,   88,   65,   89,   90,  103,   68,   66,
       67,   52,   52,   92,   69,   93,   70,  106,  107,   71,
       55,  216,   55,   50,   50,  215,  216,  216,   72,  214,
      213,   52,   52,   94,   73,   95,   74,  108,  109,   75,

      215,  216,   96,  110,  111,  214,  216,  216,   97,  115,
      142,   98,  142,  112,  213,  116,  142,  117,  113,  114,
      118,  127,   99,  143,  136,  143,  136,  128,  100,  143,
      129,  101,   44,   44,   44,   44,   44,   44,   45,   45,
       45,   45,   45,   45,   45,  216,  216,  216,  216,   45,
       91,   91,   91,   91,   91,   91,   91,  193,  193,  193,
      193,  193,  193,  193,  136,  209,  136,  208,  207,   45,
      135,  136,  135,  136,  137,  137,  137,  137,  137,  137,
      137,  135,  138,  135,  138,  139,  139,  139,  139,  139,
      139,  139,  194,  194,  194,  194,  194,  194,  194,  193,

      193,  193,  193,  193,  193,  193,   91,   91,  192,  192,
      206,  205,  204,  203,  202,  201,  212,  211,  210,  209,
      209,  208,  208,  207,  206,  207,  206,  205,  205,  204,
      204,  203,  203,  202,  201,  202,  201,  200,  199,  198,
      197,  196,  195,  176,  191,  190,  189,  188,  168,  187,
      186,  164,  185,  162,  161,  184,  158,  183,  155,  182,
      151,  150,  181,  180,  179,  178,  140,  176,  177,  176,
      175,  174,  173,  172,  171,  168,  170,  169,  168,  167,
      166,  164,  165,  164,  163,  162,  162,  161,  161,  160,
      159,  158,  158,  157,  156,  155,  155,  154,  151,  150,

      153,  152,  151,  150,  149,  148,  147,  146,  140,  145,
      144,  141,  140,  130,   90,   89,  124,  123,  121,  120,
      119,  216,    3,  216,  216,  216,  216,  216,  216,  216,
      216,  216,  216,  216,  216,  216,  216,  216,  216,  216,
      216,  216,  216,  216,  216,  216,  216,  216,  216,  216,
      216,  216,  216,  216,  216,  216,  216,  216,  216,  216,
      216,  216,  216,  216,  216,  216,  216,  216,  216,  216,
      216,  216,  216,  216,  216,  216,  216
    } ;

static yyconst flex_int16_t yy_chk[478] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    9,   14,    9,
        9,    9,   10,  212,   10,   10,   10,   10,   10,   10,
       10,    7,    7,    7,    7,    7,    7,    8,   14,    8,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,

        8,    8,    8,   25,   15,   25,   32,   32,   37,   40,
       37,   40,   41,   41,   43,   43,  211,    8,    8,    8,
        8,    8,    8,   11,   15,   11,   11,   11,   11,   11,
       11,   11,   11,   11,   11,   11,   11,   11,   11,   16,
       17,   17,   18,   19,   11,   20,   21,   24,  210,   11,
       11,   55,   55,   11,   11,   11,   11,   11,   11,   16,
       17,   17,   18,   19,   11,   20,   21,   24,   13,   11,
       11,   12,   12,   22,   13,   22,   13,   26,   26,   13,
       50,   12,   50,   50,   50,  200,   12,   12,   13,  199,
      198,   12,   12,   22,   13,   22,   13,   26,   26,   13,

      197,   12,   23,   27,   27,  196,   12,   12,   23,   28,
       60,   23,   65,   27,  195,   28,  112,   28,   27,   27,
       28,   38,   23,   60,  135,   65,  135,   38,   23,  112,
       38,   23,   44,   44,   44,   44,   44,   44,   45,   45,
       45,   45,   45,   45,   45,  137,  139,  137,  139,   45,
       91,   91,   91,   91,   91,   91,   91,  136,  136,  136,
      136,  136,  136,  136,  192,  191,  192,  188,  187,   45,
       46,   46,   46,   46,   46,   46,   46,   46,   46,   46,
       46,   53,   53,   53,   53,   53,   53,   53,   53,   53,
       53,   53,  138,  138,  138,  138,  138,  138,  138,  193,

      193,  193,  193,  193,  193,  193,  217,  217,  218,  218,
      186,  185,  184,  183,  182,  181,  180,  179,  178,  177,
      175,  172,  171,  170,  169,  167,  166,  165,  163,  160,
      159,  157,  156,  154,  153,  152,  149,  148,  147,  146,
      145,  144,  141,  134,  133,  132,  131,  130,  129,  128,
      127,  126,  125,  124,  123,  122,  121,  120,  119,  118,
      117,  116,  115,  114,  113,  111,  110,  109,  108,  107,
      106,  105,  104,  103,  102,  101,  100,   99,   98,   97,
       96,   95,   94,   93,   92,   88,   87,   86,   85,   84,
       83,   81,   80,   79,   78,   77,   76,   75,   74,   73,

       72,   71,   70,   69,   68,   67,   66,   64,   63,   62,
       61,   59,   58,   39,   36,   35,   34,   33,   31,   30,
       29,    3,  216,  216,  216,  216,  216,  216,  216,  216,
      216,  216,  216,  216,  216,  216,  216,  216,  216,  216,
      216,  216,  216,  216,  216,  216,  216,  216,  216,  216,
      216,  216,  216,  216,  216,  216,  216,  216,  216,  216,
      216,  216,  216,  216,  216,  216,  216,  216,  216,  216,
      216,  216,  216,  216,  216,  216,  216
    } ;

extern int ce_flex_debug;
int ce_flex_debug = 0;

static yy_state_type *yy_state_buf=0, *yy_state_ptr=0;
static char *yy_full_match;
static int yy_lp;
#define REJECT \
{ \
*yy_cp = (yy_hold_char); /* undo effects of setting up cetext */ \
yy_cp = (yy_full_match); /* restore poss. backed-over text */ \
++(yy_lp); \
goto find_rule; \
}

#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *cetext;
#line 1 "./ce_tokeniser.l"
#line 4 "./ce_tokeniser.l"

/*  $Header: /cvs/gnome/gcalctool/gcalctool/ce_tokeniser.l,v 1.16 2006/12/15 15:27:37 richb Exp $
 *
 *  Copyright (C) 2004-2008 Sami Pietila
 *
 *  This program is free software; you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation; either version 2, or (at your option)
 *  any later version.
 *           
 *  This program is distributed in the hope that it will be useful, but 
 *  WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU 
 *  General Public License for more details.
 *           
 *  You should have received a copy of the GNU General Public License
 *  along with this program; if not, write to the Free Software
 *  Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA
 *  02111-1307, USA.
 */

#include <stdlib.h>
#include <locale.h>
#include <string.h>
#include <sys/types.h>
#include "calctool.h"
#include "display.h"
#include "mp.h"
#include "functions.h" /* FIXME: Needed for gc_strdup() */
#include "ce_parser.h"
#include "ce_parser.tab.h"
#define YY_NO_INPUT 1
#line 720 "lex.ce.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int celex_destroy (void );

int ceget_debug (void );

void ceset_debug (int debug_flag  );

YY_EXTRA_TYPE ceget_extra (void );

void ceset_extra (YY_EXTRA_TYPE user_defined  );

FILE *ceget_in (void );

void ceset_in  (FILE * in_str  );

FILE *ceget_out (void );

void ceset_out  (FILE * out_str  );

int ceget_leng (void );

char *ceget_text (void );

int ceget_lineno (void );

void ceset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int cewrap (void );
#else
extern int cewrap (void );
#endif
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( cetext, celeng, 1, ceout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( cein )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( cein ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, cein))==0 && ferror(cein)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(cein); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int celex (void);

#define YY_DECL int celex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after cetext and celeng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 53 "./ce_tokeniser.l"


#line 908 "lex.ce.c"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

        /* Create the reject buffer large enough to save one state per allowed character. */
        if ( ! (yy_state_buf) )
            (yy_state_buf) = (yy_state_type *)cealloc(YY_STATE_BUF_SIZE  );
            if ( ! (yy_state_buf) )
                YY_FATAL_ERROR( "out of dynamic memory in celex()" );

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! cein )
			cein = stdin;

		if ( ! ceout )
			ceout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			ceensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				ce_create_buffer(cein,YY_BUF_SIZE );
		}

		ce_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of cetext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);

		(yy_state_ptr) = (yy_state_buf);
		*(yy_state_ptr)++ = yy_current_state;

yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 217 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			*(yy_state_ptr)++ = yy_current_state;
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 423 );

yy_find_action:
		yy_current_state = *--(yy_state_ptr);
		(yy_lp) = yy_accept[yy_current_state];
find_rule: /* we branch to this label when backing up */
		for ( ; ; ) /* until we find what rule we matched */
			{
			if ( (yy_lp) && (yy_lp) < yy_accept[yy_current_state + 1] )
				{
				yy_act = yy_acclist[(yy_lp)];
					{
					(yy_full_match) = yy_cp;
					break;
					}
				}
			--yy_cp;
			yy_current_state = *--(yy_state_ptr);
			(yy_lp) = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
case 1:
YY_RULE_SETUP
#line 55 "./ce_tokeniser.l"
{return tABS;}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 56 "./ce_tokeniser.l"
{return tACOSH;}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 57 "./ce_tokeniser.l"
{return tACOS;}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 58 "./ce_tokeniser.l"
{return tAND;}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 59 "./ce_tokeniser.l"
{return tANS;}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 60 "./ce_tokeniser.l"
{return tASINH;}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 61 "./ce_tokeniser.l"
{return tASIN;}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 62 "./ce_tokeniser.l"
{return tATANH;}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 63 "./ce_tokeniser.l"
{return tATAN;}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 64 "./ce_tokeniser.l"
{return tCBRT;}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 65 "./ce_tokeniser.l"
{return tCHS;}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 66 "./ce_tokeniser.l"
{return tCLR;}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 67 "./ce_tokeniser.l"
{return tCOSH;}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 68 "./ce_tokeniser.l"
{return tCOS;}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 69 "./ce_tokeniser.l"
{return tEXP;}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 70 "./ce_tokeniser.l"
{return tFRAC;}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 71 "./ce_tokeniser.l"
{return tINT;}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 72 "./ce_tokeniser.l"
{return tLN;}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 73 "./ce_tokeniser.l"
{return tLOG10;}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 74 "./ce_tokeniser.l"
{return tLOG2;}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 75 "./ce_tokeniser.l"
{return tMOD;}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 76 "./ce_tokeniser.l"
{return tNOT;}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 77 "./ce_tokeniser.l"
{return tOR;}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 78 "./ce_tokeniser.l"
{return tPI;}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 79 "./ce_tokeniser.l"
{return tRAND;}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 80 "./ce_tokeniser.l"
{return tRCL;}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 81 "./ce_tokeniser.l"
{return tSINH;}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 82 "./ce_tokeniser.l"
{return tSIN;}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 83 "./ce_tokeniser.l"
{return tSQRT;}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 84 "./ce_tokeniser.l"
{return tSTO;}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 85 "./ce_tokeniser.l"
{return tTANH;}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 86 "./ce_tokeniser.l"
{return tTAN;}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 87 "./ce_tokeniser.l"
{return tU16;}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 88 "./ce_tokeniser.l"
{return tU32;}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 89 "./ce_tokeniser.l"
{return tXNOR;}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 90 "./ce_tokeniser.l"
{return tXOR;}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 92 "./ce_tokeniser.l"
{
celval.integer = atoi(cetext+1);  
return tREG;
}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 98 "./ce_tokeniser.l"
{
if (v->base == HEX) REJECT;
if (strlen(cetext) > MAX_DIGITS) parser_state.error = -PARSER_ERR_TOO_LONG_NUMBER;
mp_set_from_string(cetext, basevals[v->base], celval.int_t);
return tNUMBER;
}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 105 "./ce_tokeniser.l"
{
if (v->base != BIN) REJECT;
if (strlen(cetext) > MAX_DIGITS) parser_state.error = -PARSER_ERR_TOO_LONG_NUMBER;
mp_set_from_string(cetext, basevals[v->base], celval.int_t);
return tNUMBER;
}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 112 "./ce_tokeniser.l"
{
if (v->base != OCT) REJECT;
if (strlen(cetext) > MAX_DIGITS) parser_state.error = -PARSER_ERR_TOO_LONG_NUMBER;
mp_set_from_string(cetext, basevals[v->base], celval.int_t);
return tNUMBER;
}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 119 "./ce_tokeniser.l"
{
if (v->base != DEC) REJECT;
if (strlen(cetext) > MAX_DIGITS) parser_state.error = -PARSER_ERR_TOO_LONG_NUMBER;
mp_set_from_string(cetext, basevals[v->base], celval.int_t);
return tNUMBER;
}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 126 "./ce_tokeniser.l"
{
if (v->base != HEX) REJECT;
if (strlen(cetext) > MAX_DIGITS) parser_state.error = -PARSER_ERR_TOO_LONG_NUMBER;
mp_set_from_string(cetext, basevals[v->base], celval.int_t);
return tNUMBER;
}
	YY_BREAK
case 43:
/* rule 43 can match eol */
YY_RULE_SETUP
#line 134 "./ce_tokeniser.l"

	YY_BREAK
case 44:
YY_RULE_SETUP
#line 135 "./ce_tokeniser.l"
{return *cetext; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 137 "./ce_tokeniser.l"
ECHO;
	YY_BREAK
#line 1254 "lex.ce.c"
			case YY_STATE_EOF(INITIAL):
				yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed cein at a new source and called
			 * celex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = cein;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( cewrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * cetext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of celex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), (size_t) num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			cerestart(cein  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) cerealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	(yy_state_ptr) = (yy_state_buf);
	*(yy_state_ptr)++ = yy_current_state;

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 217 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		*(yy_state_ptr)++ = yy_current_state;
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    
	register YY_CHAR yy_c = 1;
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 217 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 216);
	if ( ! yy_is_jam )
		*(yy_state_ptr)++ = yy_current_state;

	return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					cerestart(cein );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( cewrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve cetext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void cerestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        ceensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            ce_create_buffer(cein,YY_BUF_SIZE );
	}

	ce_init_buffer(YY_CURRENT_BUFFER,input_file );
	ce_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void ce_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		cepop_buffer_state();
	 *		cepush_buffer_state(new_buffer);
     */
	ceensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	ce_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (cewrap()) processing, but the only time this flag
	 * is looked at is after cewrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void ce_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	cein = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE ce_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) cealloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in ce_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) cealloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in ce_create_buffer()" );

	b->yy_is_our_buffer = 1;

	ce_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with ce_create_buffer()
 * 
 */
    void ce_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		cefree((void *) b->yy_ch_buf  );

	cefree((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a cerestart() or at EOF.
 */
    static void ce_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	ce_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then ce_init_buffer was _probably_
     * called from cerestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void ce_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		ce_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void cepush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	ceensure_buffer_stack();

	/* This block is copied from ce_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from ce_switch_to_buffer. */
	ce_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void cepop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	ce_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		ce_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void ceensure_buffer_stack (void)
{
	int num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)cealloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in ceensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)cerealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in ceensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE ce_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) cealloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in ce_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	ce_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to celex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       ce_scan_bytes() instead.
 */
YY_BUFFER_STATE ce_scan_string (yyconst char * yystr )
{
    
	return ce_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to celex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE ce_scan_bytes  (yyconst char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) cealloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in ce_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = ce_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in ce_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up cetext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		cetext[celeng] = (yy_hold_char); \
		(yy_c_buf_p) = cetext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		celeng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int ceget_lineno  (void)
{
        
    return celineno;
}

/** Get the input stream.
 * 
 */
FILE *ceget_in  (void)
{
        return cein;
}

/** Get the output stream.
 * 
 */
FILE *ceget_out  (void)
{
        return ceout;
}

/** Get the length of the current token.
 * 
 */
int ceget_leng  (void)
{
        return celeng;
}

/** Get the current token.
 * 
 */

char *ceget_text  (void)
{
        return cetext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void ceset_lineno (int  line_number )
{
    
    celineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see ce_switch_to_buffer
 */
void ceset_in (FILE *  in_str )
{
        cein = in_str ;
}

void ceset_out (FILE *  out_str )
{
        ceout = out_str ;
}

int ceget_debug  (void)
{
        return ce_flex_debug;
}

void ceset_debug (int  bdebug )
{
        ce_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from celex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

    (yy_state_buf) = 0;
    (yy_state_ptr) = 0;
    (yy_full_match) = 0;
    (yy_lp) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    cein = stdin;
    ceout = stdout;
#else
    cein = (FILE *) 0;
    ceout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * celex_init()
     */
    return 0;
}

/* celex_destroy is for both reentrant and non-reentrant scanners. */
int celex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		ce_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		cepop_buffer_state();
	}

	/* Destroy the stack itself. */
	cefree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    cefree ( (yy_state_buf) );
    (yy_state_buf)  = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * celex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *cealloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *cerealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void cefree (void * ptr )
{
	free( (char *) ptr );	/* see cerealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 137 "./ce_tokeniser.l"



void
reset_ce_tokeniser()
{
ce_flush_buffer(YY_CURRENT_BUFFER);

}

#if 0
// EMPTY BLOCK



#endif

