BINARY_FILE = test
COMPILER = gcc

test123:
	

make: 
	@echo "Compiling ........."
	$(COMPILER) -o $(BINARY_FILE) test.c test_lib.c

install:
	@echo "installing ......"

clean: 
	@echo "Cleaning ...." 
	@rm -f *.o
	@rm $(BINARY_FILE)
 
