BINARY_FILE = KeKe
COMPILER = javac

all:
	@echo "onon"

compile:
	@echo "Compiling.........."
	$(COMPILER) $(BINARY_FILE).java
	
test:
	java  $(BINARY_FILE) 
	
clean:
	
	@echo "Cleaning....."
	@rm -f *.class
	
